name: Package GUI with Pyinstaller

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on:  ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-22.04, ubuntu-20.04, 
          windows-2022, windows-2019, 
          macos-12, macos-11,
          ]
        python-version: ["3.11"]
        dysh-tag: ["0.2.0b"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install https://github.com/GreenBankObservatory/dysh/archive/refs/tags/${{ matrix.dysh-tag }}.zip
      - name: Package GUI with PyInstaller
        run: |
          cd src
          pyinstaller app.py